# Integer-N PLL Operation for SKY130

An integer-N PLL forces the output clock to be an exact integer multiple of the reference clock by comparing the reference path and the divided feedback path, then adjusting the VCO until both match in phase and frequency [1][2].

## Simple circuit view

- The **reference clock** is the clean input clock, often from a crystal or external source, and it may be divided to a comparison rate inside the PLL [1].
- The **VCO output** is the high-frequency clock generated by the loop, and part of this output is fed back through a divide-by-N block [1].
- The phase-frequency detector compares the reference clock with the **feedback clock** from the divider, then drives the charge pump and loop filter so the VCO speeds up or slows down as needed [1].

## Divide-by-N relation

- In lock, the divider makes the feedback clock equal to the reference comparison clock, so $$f_{VCO} / N = f_{REF}$$ at the phase detector input [1][2].
- Therefore, $$f_{VCO} = N \cdot f_{REF}$$, which is the defining relation of an integer-N PLL [1][2].
- If an output divider is added after the VCO, the final output frequency is a further scaled version of the VCO frequency [1].

## Phase and frequency locking

- At startup, the reference and feedback clocks are usually not aligned, so the phase detector produces correction pulses that move the VCO control voltage [1].
- The loop continues adjusting until both clocks have the same frequency and a constant phase relationship; this condition is called lock [1].
- In practical SKY130 designs, stable locking depends on the combined behavior of the phase detector, charge pump, loop filter, VCO gain, and divider ratio [3][4].

## Lock time

- **Lock time** is the time the PLL needs to settle from reset or after a frequency step into stable operation [2][5].
- Lock time increases when the loop bandwidth is too narrow, the frequency jump is large, or the VCO control node must move a long distance [2][5].
- For SKY130, a practical design check is to confirm lock time across process, voltage, and temperature corners, not just in typical simulation [3][4].

## Practical SKY130 notes

Think of the PLL as a feedback servo: the reference clock sets the target, the divider scales the output down for comparison, and the loop continuously corrects the VCO until the divided feedback matches the reference [1][2]. For a compact SKY130 design, focus on adequate VCO tuning range, stable loop dynamics, and acceptable lock time across PVT corners [3][4].
